<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="R_Yamini" failures="1" tests="4" name="runner.TestRunner_Login" time="105.874" errors="0" timestamp="2025-09-10T19:40:20 IST" skipped="0">
  <testcase classname="runner.TestRunner_Login" name="runScenario" time="43.082">
    <failure message="Login was not successful! expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Login was not successful! expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at stepdefinitions.Login_StepDef.the_user_should_be_logged_in_successfully(Login_StepDef.java:81)
at âœ½.the user should be logged in successfully(file:///C:/Users/yamin/git/NOBROKER_TEST_APPLICATION/NOBROKER_TEST_APPLICATION/src/test/resources/features/login.feature:38)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.TestRunner_Login" name="runScenario" time="7.326"/>
  <testcase classname="runner.TestRunner_Login" name="runScenario" time="47.866"/>
  <testcase classname="runner.TestRunner_Login" name="runScenario" time="7.600"/>
</testsuite> <!-- runner.TestRunner_Login -->
